CacheDir: "./modules"
Branch: "main"
modules:
  vpc:
    repo:  "git@github.com:kevinalmansa/terrafile"
    tag: "v1.0.1"

  iam_role:
    repo:  "git@github.com:kevinalmansa/container-scanner"
    branch: "dev"

